on:
  push:
    branches:
      - 'master'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name : Clean
        run: |
          rm -rf *
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
          ref: '4.1.x'
      - name: Automatic Rebase
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin
          git config --local user.email "github-actions@users.noreply.github.com";
          git config --local user.name  "GitHub Actions";
          git rebase origin/master --stat -m -s recursive -X theirs
          git push --force-with-lease
          
