on:
  push:
    branches:
      - 'master'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: '4.1.x'
      - name: Rebase
        run: |
          git pull
          git rebase origin/master
          git push --force-with-lease
          
