on:
  push:
    branches:
      - 'master'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Rebase
        run: |
          git pull
          git rebase --onto '4.1.x' --stat
          git push --force-with-lease
          
