on:
  push:
    branches:
      - 'master'

jobs:
  mirror_job:
    runs-on: ubuntu-latest
    name: Mirror master branch to 4.1.x branch
    steps:
    - name: Mirror action step
      id: mirror
      uses: google/mirror-branch-action@v1.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        source: 'master'
        dest: '4.1.x'
