on:
  push:
    branches:
      - 'master'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name : Clean
        run: |
          rm -rf *
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
          ref: '4.1.x'
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
          
